concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  build-celestic:
    runs-on: ubuntu-latest
    steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
    - name: Checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 1
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
    - name: Cachix
      uses: cachix/cachix-action@master
      with:
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
        name: cutehaus
    - name: Build celestic
      run: nix build --accept-flake-config --print-out-paths .#nixosConfigurations.celestic.config.system.build.toplevel
  build-eterna:
    runs-on: ubuntu-latest
    steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
    - name: Checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 1
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
    - name: Cachix
      uses: cachix/cachix-action@master
      with:
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
        name: cutehaus
    - name: Build eterna
      run: nix build --accept-flake-config --print-out-paths .#nixosConfigurations.eterna.config.system.build.toplevel
  build-jubilife:
    runs-on: ubuntu-latest
    steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
    - name: Checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 1
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
    - name: Cachix
      uses: cachix/cachix-action@master
      with:
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
        name: cutehaus
    - name: Build jubilife
      run: nix build --accept-flake-config --print-out-paths .#nixosConfigurations.jubilife.config.system.build.toplevel
  build-oreburgh:
    runs-on: ubuntu-latest
    steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
    - name: Checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 1
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
    - name: Cachix
      uses: cachix/cachix-action@master
      with:
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
        name: cutehaus
    - name: Build oreburgh
      run: nix build --accept-flake-config --print-out-paths .#nixosConfigurations.oreburgh.config.system.build.toplevel
  build-snowpoint:
    runs-on: ubuntu-latest
    steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
    - name: Checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 1
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
    - name: Cachix
      uses: cachix/cachix-action@master
      with:
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
        name: cutehaus
    - name: Build snowpoint
      run: nix build --accept-flake-config --print-out-paths .#nixosConfigurations.snowpoint.config.system.build.toplevel
  build-solaceon:
    runs-on: ubuntu-latest
    steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
    - name: Checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 1
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
    - name: Cachix
      uses: cachix/cachix-action@master
      with:
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
        name: cutehaus
    - name: Build solaceon
      run: nix build --accept-flake-config --print-out-paths .#nixosConfigurations.solaceon.config.system.build.toplevel
  build-twinleaf:
    runs-on: ubuntu-latest
    steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
    - name: Checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 1
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
    - name: Cachix
      uses: cachix/cachix-action@master
      with:
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
        name: cutehaus
    - name: Build twinleaf
      run: nix build --accept-flake-config --print-out-paths .#nixosConfigurations.twinleaf.config.system.build.toplevel
name: build-nixos
'on':
  push:
    paths-ignore:
    - '**/*.md'
    - .github/**
    - _img/**
  workflow_dispatch: {}
